# Generated by Django 4.2 on 2023-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='a1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='q1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
